### ISSUE TITLE
Avatar Performance Behavior

### ISSUE THREAD

**Issue by rohrlach** [upstage-org/limelight#10]
Players should be able to take hold of avatars and control them on the stage.
**Acceptance Criteria**
- [ ] Players can pick up (hold) an avatar
- [ ] Players can click on the stage to place the avatar they are holding
- [ ] Avatars should move on the stage to where the player that is holding it has clicked
- [ ] Players can only hold one avatar at a time.
- [ ] Players can release (drop) avatars they are holding
- [ ] Players who use the chat while holding an avatar should see their message appear as a speech bubble above the avatar they are holding.

**Comment by helenvarley** [comment]
last point, "Players who use the chat while holding an avatar should see their message appear as a speech bubble above the avatar they are holding." - everyone on the stage should see the speech bubble, not only the player holding the avatar (just to clarify).

**Comment by helenvarley** [comment]
do we also want "Player can flip / rotate the avatar they are holding" ?
& "player can change the name of the avatar they are holding" ?

**Comment by rohrlach** [comment]
Yes we do, however I think I'll raise these enhancements as separate issues.  Let's just get avatars on the stage first :)

**Comment by vickis** [comment]
agree ;)

**Comment by rohrlach** [comment]
On further analysis, this will be broken down into smaller issues
