### ISSUE TITLE
Avatar Index - Panel UX

### ISSUE THREAD

**Issue by rohrlach** [upstage-org/limelight#102]
Avatars should be represented as tiles with a thumbnail and quick actions for each.

**Comment by helenvarley** [comment]
i am not convinced about the necessity of thumbnails - it will make the list very long to scroll down. i find the current layout in UpStage v3 pretty good - you can easily filter & then click on an item in order to see a thumbnail.

**Comment by helenvarley** [comment]
being able to sort/filter by user/uploader, type, stage & date is important.

**Comment by helenvarley** [comment]
do we need separate panels for avatars & sounds? can't it be all media, with option to sort/filter by type? (as in UpStage v3)

**Comment by rohrlach** [comment]
Yes we can - raise an issue for it 🙂
