### ISSUE TITLE
Avatar Index - Table UX

### ISSUE THREAD

**Issue by rohrlach** [upstage-org/limelight#104]
Users should have the ability to toggle a tabled list of avatars rather than the panelled list (which will remain the default)

**Comment by helenvarley** [comment]
i prefer tabled list as default (assume by panelled list you mean with the larger thumbnails?) - since as soon as there is more than a dozen or so avatars, having all the thumbnails displaying will be too much.

**Comment by rohrlach** [comment]
Righto

**Comment by vickis** [comment]
yes toggle impt so users can decide which suits them best :)
