### ISSUE TITLE
Shout

### ISSUE THREAD

**Issue by rohrlach** [upstage-org/limelight#106]
When a Player is using chat:

- [x] Prepending their message with '!' should enable shout mode
- [x] Shouted messages should appear in the chat window as bold and in 0xff0000
- [x] There should also be a checkbox modifier near the input box that enables shout

Relates to #72 supersedes #7

**Comment by rohrlach** [comment]
Shout is ready for testing (deploys in 45 mins)

**Comment by helenvarley** [comment]
tested & working :)
@vickis - what do you think about the shout command staying active until you unclick the box? might be useful ... you can type the ! yourself & that only does the one line, so you don't need to remember to turn it off. or if you know you want to keep shouting for a while, you could use the checkbox to have it persist ... ?

**Comment by vickis** [comment]
Yes sounds like a useful mod for the angry players ;)

**Comment by vickis** [comment]
yes makes sense 
for the angry young players …

like that you can use it once or twice - or repeatedly without having to remember the command = useful!

**Comment by rohrlach** [comment]
I may have a better idea here - will see what I can sort out

**Comment by rohrlach** [comment]
Can we consider this completed?

**Comment by vickis** [comment]
yes = great! :)
