### ISSUE TITLE
Avatar List - default display

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/limelight#107]
the default display for the avatar list (https://limelight.upstage.org.nz/avatars) should NOT be the large icon; once there are more than a handful of avatars, this will be a really annoying way to view the media. the default should be a LIST, & probably without thumbnail - similar to how it is in UpStage v3 - & ideally sortable - by name, user/uploader (not currently shown at all), tags, stage, upload date.

**Comment by rohrlach** [comment]
The reason I defaulted to the panels is that the panels interface is a LOT nicer on smaller screens.  Particularly for Avatars if you consider this scenario:

"I want to have an Avatar of myself so I use my phone to snap a photo then upload it directly"

**Comment by helenvarley** [comment]
i think that's a good argument for having a nice preview show in the upload process; but for browsing media, i still think the list will be much easier to use in list format. you can see already that with only 3 items, the screen is already almost full. on my 14" screen, i will be able to see 4-5 items without scrolling. on live.upstage.org.nz there are currently 75 media items (that includes sound & audio & streams) & that's from only 2 shows, one workshop, one presentation & the walkthrough stage. on the previous installation of UpStage v2 there must have been hundreds of media items.

**Comment by rohrlach** [comment]
Then it's settled

**Comment by vickis** [comment]
could limelight detect user and present solution based on device?

**Comment by rohrlach** [comment]
Yes of course.

In fact - I'd have done that originally except we have limited server resources so I figured if I could get away with less cycles it'd be better

**Comment by rohrlach** [comment]
Superseded: #109

**Comment by helenvarley** [comment]
the default display is still the large icons, not the list ... ??
