### ISSUE TITLE
assigning to stage

### ISSUE THREAD

**Issue by vickis** [upstage-org/limelight#112]
i went to assign the leafy gif avatar to the stage but got this
![screen shot 2017-05-08 at 7 15 10 am](https://cloud.githubusercontent.com/assets/4249450/25784283/19f25438-33be-11e7-82ee-a654de05794d.png)

**Comment by rohrlach** [comment]
Can you try it again? Could have been a timing issue with an update

**Comment by vickis** [comment]
yep still not working either in firefox or chrome...

**Comment by rohrlach** [comment]
Okay. Error actually occurs when accessing Stage Edit screen. - good catch 😇

**Comment by vickis** [comment]
Yes working - added map deleted lady godiva ... but cannot access the stage to check if they are there...
