### ISSUE TITLE
Deleting Media - red cross confusing

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/limelight#117]
the large red X button for deleting media is a bit confusing - i thought at first it was to close the edit screen & return to the media list. 
could it be a trash can icon instead? & have rollover text that says something like "delete media item" ?

the pop-up window that says "{name of media item} will be removed" is also a bit abrupt. could it say something like "Are you sure you want to delete {name of media item}?"

**Comment by vickis** [comment]
actually it seemed intuitive to me 
(+ & green for add x red for delete ) 
- agree rubbish bin more generic though 

checking before deleting is good

**Comment by helenvarley** [comment]
a red cross is also a fairly universal symbol for closing a window/pop-up/panel. that's what confused me. if it's next to the green + as it is for adding & deleting tags, it's clearer; but when it's at the top right of a screen, it can be read as a way to close the window/go back to the media list.

**Comment by rohrlach** [comment]
Will see if we have a trash icon in the pack. I agree that the wording should be a question... However the choices are currently 'cancel' and 'ok' which can't be changed without moderate effort.  I'm happy to keep this as the goal and perhaps drop it's priority for the time being

**Comment by helenvarley** [comment]
great, that seems much clearer to me :)
