### ISSUE TITLE
Theming

### ISSUE THREAD

**Issue by rohrlach** [upstage-org/limelight#119]
- [x] Modify Bootstrap theme in the UpStage colours
- [x] Theme should be able to be dropped in on top of the existing CSS without further modifications

**Comment by JoeIceCream** [comment]
@rohrlach Would you like this inside the actual stages, over the home pages or throughout the entire website?

**Comment by rohrlach** [comment]
The performance space has its own set of custom styling directives (Not using Bootstrap at all) This is for the rest of the application.

Ideally, you're just going to modify various Sass variables associated with the bootstrap-sass gem.  This means that in the application.scss file you're going to override the variables listed here:
https://github.com/twbs/bootstrap-sass/blob/master/assets/stylesheets/bootstrap/_variables.scss

**Comment by rohrlach** [comment]
Code provided by @JoeIceCream meets the criteria of this ticket and thus, I'm closing it.  @helenvarley & @vickis if you want further modifications please raise issues for them

**Comment by vickis** [comment]
super!! :)
