### ISSUE TITLE
audience chat text appears twice

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/limelight#136]
when i am not logged in, the text i type as audience appears twice when i enter it. then, when i log back in & go to the stage as a player, i only seeing the audience text once. 
so i logged out again & went back to the stage as audience, & only see the text once as well. but definitely, when i was on the stage as audience and entering text, it was showing up twice.
when i enter new text, as audience, it again shows up doubled.
![audience_chat_double](https://cloud.githubusercontent.com/assets/3437324/25994274/9330f88e-370d-11e7-9936-f25ad1b832f5.png)

**Comment by helenvarley** [comment]
woah! now it appears three times! but reload removes the extras.
![audience_chat_triples](https://cloud.githubusercontent.com/assets/3437324/25994772/877d8032-370f-11e7-8ee3-1ed1b048ee5a.png)

**Comment by rohrlach** [comment]
Could be a browser quirk on that day?

I can't recreate the issue so I'm going to close it for now.  If we can get a better idea of the specifics around when it occurs, we'll reopen

**Comment by helenvarley** [comment]
it is still appearing twice for me, when i'm on the stage as audience; i reload the stage, & the ones that were showing twice are now showing once, but then the next thing i type appears 3 times. so it's not a passing quirk. 
i just tried with the tor browser, & my text only appeared once. so maybe it's a browser issue. i'm installing chrome ... and there my text is also only appearing once. same in firefox on mac. 
so it looks like it's a browser issue - firefox on linux.

i'm going to leave this open - it's not a high priority but it would be good to try & fix it since it will be hugely annoying for any audience members using firefox on linux - & there will be some (not least of all me, when watching others shows!)

**Comment by charlie0605** [comment]
@helenvarley can you please check again if this issue still exists? Thong and I tried to replicate this issue but we couldn't get the message to duplicate. I have Chrome signed in and Firefox as audience and when sending message from Firefox it only show one line of code.

**Comment by vickis** [comment]
this is a weird legacy issue was there ever a screen grab if it happening

- thinking of how the text being spoken in a loop seemed to be set off by
the use of an exclamation mark...

**Comment by thongteav** [comment]
@vickis tested again with exclamation mark, it didn't trigger the bug.

**Comment by vickis** [comment]
Hey yeah oops
the ! triggered looping text

i was wondering if we ever screen grabbed the issue when it happened...
maybe its gone!!
:)

**Comment by helenvarley** [comment]
@vickis there are screengrabs above, i posted them when i created the issue.

i just tested now (firefox on linux) & it is not happening for me anymore. if no-one's been able to replicate then i guess it has been resolved :)

**Comment by helenvarley** [comment]
(this bug was nothing to do with using !, & it was also not the voice loop. it was audience text being printed into the chat twice & then three times).

**Comment by vickis** [comment]
yep roger that
was speculating on the cause of the re-printing

well done on resolving it team :)
