### ISSUE TITLE
avatar movement - drag & drop?

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/limelight#138]
in UpStage avatar movement has been point & click, as opposed to drag & drop. the centre of the avatar moves to where you have clicked - but it's hard to know where the centre is. it would be great if we could have more precise positioning, which drag & drop would probably give. we talked about this earlier, & the idea of having a "shadow" of the avatar, so that you could see where it was going to land when you dropped it. 
it would also be helpful to be able to use the arrow keys to move one pixel at a time.

this is not a high priority, but as soon as it comes to coding the avatars & their on-stage movement it would be good to bear this in mind.

**Comment by vickis** [comment]
Agree! :)

**Comment by blankgaming** [comment]
Hi Helen @helenvarley , For this drag and drop feature, do you mean to have the avatar dragged and dropped from the avatar tab on the stage with a shadow of the avatar or is it on the stage to have the drag and drop functionality?

**Comment by helenvarley** [comment]
@blankgaming it is mainly on the stage. however if it could also be from the avatar palette that would be quite intuitive and would mean you could also get more precise positioning with the first appearance of the avatar on the stage.

**Comment by charlie0605** [comment]
with this issue would it have to broken up a little bit?
right now players are able to draw on the canvas on any given tab. Players are currently able to drawn on canvas if they are on avatar, audio, backdrop tab. Is this meant to be implemented like this or is player only able to draw when they are on drawing tab?

**Comment by helenvarley** [comment]
players should only be able to draw on the stage when they have the drawing palette displayed. this is important as otherwise how do you distinguish between moving an avatar around & drawing? sometimes you need to have the audio palette open but still be able to move your avatar without having to switch between palettes.
this is how it's always worked in the past - that you can only draw when you have switched to the drawing palette (note: apart from the "draw on avatar" feature!) & this has worked well.

**Comment by rohrlach** [comment]
You are correct @charlie0605 however that's a bug unrelated to this issue.

This issue asks for the implementation of using "drag and drop" to move avatars

**Comment by helenvarley** [comment]
if i click on the avatar & drag it, it moves. if i click somewhere else on the stage, the avatar moves there. all good. but if i click, hold & drag somewhere else on the stage, i draw. even when i am in the avatar palette. this should not happen. i should only be able to draw when i have the drawing palette exposed (or with the draw on avatar feature, if we have that).

**Comment by rohrlach** [comment]
@helenvarley see #194
