### ISSUE TITLE
Avatar Tab in Stage Toolbox

### ISSUE THREAD

**Issue by rohrlach** [upstage-org/limelight#144]
This issue requires a tab to be added to the onstage toolbox labelled 'Avatars'
![screenshot from 2017-05-16 09-58-46](https://cloud.githubusercontent.com/assets/2830313/26109815/69761a6a-3a1e-11e7-8fb3-3f058aa60d86.png)
This box should contain a scrolling list of thumbnails/names representing each avatar assigned to the stage that is currently in use.

This is a preliminary task for #138

**Comment by JoeIceCream** [comment]
@rohrlach Hi Paul, we've just been experimenting with using the byebug debugging tool from the gem file. However we're having a problem with making the debugging code appear. We realize we're supposed to write "byebug" within the controller method, but nothing prints to the terminal when we run it. How do we see the output?

**Comment by rohrlach** [comment]
@JoeIceCream I've always used 'debugger':

```
def index
  debugger
  @collection = ...
```

```
<div>
  <% debugger %>
</div>
```

**Comment by Tawpin** [comment]
<ul class="media-list">
                    <% @stage.avatars.each do |a| %>

                        <button  id="avatarsb" class="media">
                        <%= image_tag a.source.url(:thumb), :alt => a.name,
:class => 'img-circle pull-left' %>

                        

                        </button>
                        <p></p>
                      <% end %>
                    <% end %>
                    </ul>

**Comment by helenvarley** [comment]
looks like a good start - the tab is there, i can see the avatar thumbnails, & i can click back to another tab.
can there be a rollover to show the name of the avatar? this would be useful for example if there are 2 similar avs, or like on the hentest stage the av thumbnail is not very clear.

**Comment by rohrlach** [comment]
Yep - that'll need to be a separate ticket

**Comment by rohrlach** [comment]
I believe this issue can be closed.

**Comment by vickis** [comment]
yes great see the avatars (chrome v58 on MacOS)
can't put them on stage yet tho...
