### ISSUE TITLE
mobile - no link to enter stage

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/limelight#147]
i just had a look at limelight on my mobile :) it looks pretty good, however there doesn't seem to be a way to enter a stage. should there be?
on my computer, when i'm on https://limelight.upstage.org.nz/foyer there is the heading "stages" and the link below that to "walkthrough" takes me to the stage. but on my mobile, at the same url, & seeing the same interface (e.g. i can also see "announcements" & "stats", clicking on "walkthrough" takes me to the edit screen for that stage.

**Comment by rohrlach** [comment]
This is done deliberately.  The current performance space won't work on mobile.
