### ISSUE TITLE
chat window too long

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/limelight#149]
the chat window (& stage) should resize according to the size of your browser window. 
currently on my 14" laptop (using firefox on linux) i have to scroll down to get to the chat input field (see screenshot). this might seem like a minor issue, but in performance it is actually really important that, no matter what size screen or resolution, everyone is seeing the same thing, & not having to scroll (which is disruptive).
we managed it with UpStage so it must be possible :)
![screenshot at 2017-05-16 19 22 55](https://cloud.githubusercontent.com/assets/3437324/26119430/7989404a-3a6d-11e7-9f5d-c9e83e04689c.png)

**Comment by rohrlach** [comment]
Looks like it's caused by the styling (or lack thereof) on the drawing controls

**Comment by rohrlach** [comment]
This appears to be a firefox specific issue

**Comment by helenvarley** [comment]
nope - happening in chrome as well, on both mac & linux, & also in safari:
![chrome_linux](https://cloud.githubusercontent.com/assets/3437324/26124460/c6e662f8-3a7e-11e7-96ab-e5ce9736bba2.png)
![firefox_linux](https://cloud.githubusercontent.com/assets/3437324/26124462/c6eaeb16-3a7e-11e7-80e3-e69e0a96fc73.png)
![firefox_mac](https://cloud.githubusercontent.com/assets/3437324/26124461/c6eb252c-3a7e-11e7-8437-49be0d57c843.png)
![Uploading chrome_mac.png…]()
![safari_mac](https://cloud.githubusercontent.com/assets/3437324/26124531/14220c5c-3a7f-11e7-8e19-8eff2b3ad5d3.png)

**Comment by helenvarley** [comment]
great - on firefox (linux) at least it is resizing nicely now. i will test on other browsers tomorrow, but it looks good.
but the text is now pressed up against the edge of the chat window on both sides. previously there was a nice bit of spacing there, which looks better.

**Comment by rohrlach** [comment]
Yeah, unfortunately I'm still working out the kinks. I basically had to completely reimplement the page to make some of the changes that needed to be made going forward

**Comment by rohrlach** [comment]
Can we consider this resolved?
