### ISSUE TITLE
On Stage Visual Regressions

### ISSUE THREAD

**Issue by rohrlach** [upstage-org/limelight#163]
After #161 the following are happening when in the auidence:
- [x] 'undefined' shown beside message
![screen shot 2017-05-20 at 9 24 29 pm](https://cloud.githubusercontent.com/assets/2830313/26280454/e72a302c-3da2-11e7-9d10-eba54b8643b3.png)

- [x] Large gap below input box
![screen shot 2017-05-20 at 9 24 39 pm](https://cloud.githubusercontent.com/assets/2830313/26280455/e7305358-3da2-11e7-8609-27188b8a0391.png)

**Comment by helenvarley** [comment]
i'm not seeingthe large gap below the input box, & the chat window resizing is now working, but the text is pressed right up against the edge which is not so nice.

**Comment by rohrlach** [comment]
Yes - Ended up having time to fix these two things but not the third

**Comment by rohrlach** [comment]
![screen shot 2017-05-22 at 12 22 57 am](https://cloud.githubusercontent.com/assets/2830313/26292598/2b967fb2-3e85-11e7-85c1-7dd728725831.png)

**Comment by vickis** [comment]
beautiful!

**Comment by helenvarley** [comment]
great, looking better & more readable to me :)
but to be pedantic, can there be less of a gap? i think about half the size of the gap at the moment (between the grey line & the next player name) would be sufficient to separate the texts & be readable, but also to allow the maximum amount of chat to be visible on the screen. it's quite useful to be able to read back a few lines all the time without scrolling.

**Comment by rohrlach** [comment]
@helenvarley will go out in about 10 mins (Margins are halved)
![screen shot 2017-05-22 at 11 49 36 am](https://cloud.githubusercontent.com/assets/2830313/26317236/d249e470-3ee4-11e7-8083-5ea6518a832d.png)
