### ISSUE TITLE
different links from chrome & firefox

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/limelight#167]
in firefox, on https://limelight.upstage.org.nz/, the Walkthrough link in the green "Stages" box takes you to the stage (https://limelight.upstage.org.nz/walkthrough)
in chrome, on https://limelight.upstage.org.nz/, the Walkthrough link in the green "Stages" box takes you to the stage edit interface (https://limelight.upstage.org.nz/stages/walkthrough)

this is only happening on my linux laptop, not on the mac - there both browsers link to the stage, not the edit interface, from this link. i cleared the cache in chrome, & restarted it, & it's still like this - the link on the home page is to the edit interface instead of the stage. very odd!!!

**Comment by helenvarley** [comment]
actually this may just be some quirk in my browser - the above happened when i was NOT logged in. i then logged in, & the link worked correctly to take me to the stage. so i logged out, & found it was now working correctly. so i closed the browser & reopened it & tried again, without logging in, & again it worked correctly. so i will close this issue.

**Comment by helenvarley** [comment]
oh, too wierd!!! now i'm getting it happening on my mac ... in chrome on mac, & logged in as player. 
i was in as audience, the link had worked as expected, then i logged in, & now the link in the "Stages" box is pointing to the edit interface instead of the stage!!! 
![screen shot 2017-05-22 at 9 47 54 am](https://cloud.githubusercontent.com/assets/3437324/26297639/01e712d6-3ed4-11e7-910d-0ad815f9e85d.png)

**Comment by helenvarley** [comment]
it is also happening in safari. not logged in, the stage link on the home page tries to go to the edit interface & i get the message telling me i need to be logged in. so i log in, & again the link on the home page takes me to the edit interface. 
there are other big problems once i get into the stage in safari, i'll make a separate issue for that ...

**Comment by rohrlach** [comment]
It's because of the window size. At a certain size, the interface starts to transition to a mobile interface

**Comment by rohrlach** [comment]
As mentioned in a previous ticket, because I can't guarantee the performance space will work on smaller displays, I have redirected the link.  This may (probably will) change in future - But I'm only focusing on desktop for the time being

**Comment by helenvarley** [comment]
ok, then it's a different issue. if the performance space isn't going to work on smaller displays, then ... why are we making it responsive?? surely the whole point is that people will be able to join the performance from mobiles & tablets?

**Comment by rohrlach** [comment]
It will :) 

In a sense, it already DOES - but the layout it super frustrating to deal with so we need to figure that out.

I think it won't be until we've worked through how the toolbox will collapse etc.

**Comment by helenvarley** [comment]
perhaps we need a different approach to mobiles & tablets. for example, many things will be difficult if not impossible to do without a proper keyboard, so it makes sense to think of the mobile/tablet experience as something different. 
i will open a new issue for this bcos i think it needs some deep thinking/discussing :)

**Comment by rohrlach** [comment]
#171
