### ISSUE TITLE
stage display in safari

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/limelight#168]
disclaimer: i have quite an old version of safari (5.1.10) & can't upgrade it on my mac. @vickis - do you have a newer version? if so can you please test this on safari on your mac?

at first, the stage doesn't appear to display at all - the screen is completely blank. but the scroll bar is there on the right, so i scroll ... & then the chat window & tools appear - on the LEFT of the screen.
& it seems like it's the entire chat log - i have to scroll a long way down to get to the input field.
![screen shot 2017-05-22 at 9 58 43 am](https://cloud.githubusercontent.com/assets/3437324/26297938/7c22f0e6-3ed5-11e7-8e0f-bd5b7cef8d76.png)
![screen shot 2017-05-22 at 9 58 38 am](https://cloud.githubusercontent.com/assets/3437324/26297939/7c27ff50-3ed5-11e7-8d4c-7b0b8f861200.png)
![screen shot 2017-05-22 at 9 58 54 am](https://cloud.githubusercontent.com/assets/3437324/26297937/7c22355c-3ed5-11e7-9e49-58eb3988957e.png)

**Comment by vickis** [comment]
the appearance of the stage looks as expected ie great safari 9.0.3 (mac os 10.11.3
