### ISSUE TITLE
Chat Links

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/limelight#17]
hyperlinks in the chat window should open in a new browser tab when clicked on, without any buggy stuff happening in the url as does in UpStage v3!!

**Comment by rohrlach** [comment]
**Story: As a user of any kind, I must be able to share a link via chat**

- [ ] Software must accurately identify URLs sent via chat
- [ ] When links are displayed in the chat log, they must indicate that they are clickable
- [ ] When a user clicks on a link in the chat log, the link must be followed in a new tab

**Comment by helenvarley** [comment]
should we also add that people can enter links either as www.blahblahblah, or http://www... & that both will become the correct link? bcos people are likely to enter links both ways, with or without the http.

**Comment by rohrlach** [comment]
Yes of course, it won't a frail parsing system.  I won't accept anything that isn't battle tested

**Comment by rohrlach** [comment]
Solved by #51

**Comment by helenvarley** [comment]
this is all looking great :)
however, audience aren't able to post clickable links. it's quite important that they can, as often audience want to contribute links that they have found.
(we have NEVER had a problem in 14 years of UpStage, but it occurs to me that it could be useful for players to be able to remove links posted by audience - e.g. if someone puts in links that are advertising, porn, or otherwise inappropriate. i guess this should be a separate issue?)

**Comment by rohrlach** [comment]
@helenvarley Yes - Separate issue for removing links
@Tawpin - Please amend so that audience members can post links

**Comment by rohrlach** [comment]
@Tawpin:
You simply need to autolink all message.content references
```
_message.html.erb

<div id = "message">
    <% @user = User.find_by_id(message.sender_id) %>
    <% if (@user != nil) %>
        <% if message.message_type == 'broadcast' %> 
            <p class="player"><%= @user.nickname %> : <%= auto_link(message.content, html: { target: '_blank' }) %></p>
        <% else %>
            <p class ="shoutToChat"><%= @user.nickname %> : <%= message.content %></p>
        <% end %>
    <% else %>
     <p class="audience"> Audience : <%= message.content %></p>
    <% end %>
</div>
```

**Comment by rohrlach** [comment]
Rework is due to be deployed at 10am ET

**Comment by helenvarley** [comment]
looking good - have tested & chat links work with the shout command, and when input by audience :)
note that when we have the think command as well, links should also work in that ... & if we are still able to have the splash message that shows up at the top of the blank chat window, it would also be good for links to work in that too ... (separate issues ... ???)

**Comment by rohrlach** [comment]
Yes - Separate :)

**Comment by rohrlach** [comment]
@helenvarley Feel free to close this issue if you are happy with it (assuming extension issues down the road
