### ISSUE TITLE
Play Audio

### ISSUE THREAD

**Issue by rohrlach** [upstage-org/limelight#183]
Requires #157 to be complete

When a player clicks on an audio button in the audio tab of the toolbox, all users connected to that stage should hear the audio file play once.

**Comment by helenvarley** [comment]
unless it is set to loop.

**Comment by helenvarley** [comment]
note: in UpStage, there was the problem that if someone entered the stage after an audio file had been started, they did not hear it. Ideally, late-comers or someone who's had to reload for some reason, should be able to hear the audio file on entering, coming in at the same point that everyone else is at. i realise this is pretty difficult, but if it's possible to achieve it would be great.

**Comment by rohrlach** [comment]
Agree.

Both that and loop are separate things though

**Comment by blankgaming** [comment]
![error](https://user-images.githubusercontent.com/22442427/27999477-a5d6e89e-6571-11e7-9938-5af95e3a5777.png) 

![code](https://user-images.githubusercontent.com/22442427/27999490-d5393fc4-6571-11e7-980a-e2d05dac7341.png)


@rohrlach  Hi Paul, apologies for not giving any update last week, Joe and I have been busy with part time work and other commitments wasnt able to work on UpStage for a while. 

We manage to get the audio control to get the audio source however when we tried to play it there was an error where the audio type is not supported. We tried "<source src..." for the audio type declaration, Do you know of any other approach we could use?

**Comment by rohrlach** [comment]
@blankgaming Can you push your working branch up so I can see what you've done?

**Comment by rohrlach** [comment]
Works on Chrome 60/Windows 10, macOS Sierra

**Comment by helenvarley** [comment]
works in firefox on linux :)

**Comment by rohrlach** [comment]
Assume we're accepting this.
