### ISSUE TITLE
Avatar Movement

### ISSUE THREAD

**Issue by rohrlach** [upstage-org/limelight#188]
Once an avatar has been placed on the stage, the player holding it can click elsewhere on the stage to move the avatar to that point.

**Comment by helenvarley** [comment]
works on firefox and chrome on linux :+1:

**Comment by vickis** [comment]
works on chrome on OS 
but firefox on OS still only access the stage edit screen  through clinking on a stage link....

**Comment by rohrlach** [comment]
@vickis do you have the window maximized?
