### ISSUE TITLE
Avatar Speech Bubbles

### ISSUE THREAD

**Issue by rohrlach** [upstage-org/limelight#190]
If a player is holding an avatar and that avatar is on the stage - Whatever that player enters into the chat should be displayed in a speech bubble above the avatar.  Styling for chat modifiers must be followed.

**Comment by charlie0605** [comment]
@helenvarley @vickis @rohrlach 
I've got the speech bubble drawing like this
![image](https://user-images.githubusercontent.com/25602185/40157631-3d488a76-59f4-11e8-9eb9-c0c0f99daab4.png)

The normal speech can adjust itself according to the amount of text you type.
![image](https://user-images.githubusercontent.com/25602185/40157642-4908853c-59f4-11e8-8641-fef6df683f1b.png)


For Shout Im having trouble drawing it like the old UpStage would something like this be ok?
![image](https://user-images.githubusercontent.com/25602185/40157737-c4d125ac-59f4-11e8-969a-25fd71c31155.png)

If the shout is drawn like this it will also allow height to be automatically adjusted when long message is sent.
![image](https://user-images.githubusercontent.com/25602185/40157822-23dabdb0-59f5-11e8-9b15-ecb1cd9dfd5d.png)


The speech bubble will stay on the stage for 3 seconds and disappear is that long enough?

**Comment by rohrlach** [comment]
That looks great 😄 Could we perhaps have it show for 5 seconds? Also, can the shout text be bold?

**Comment by helenvarley** [comment]
looking good. previously the speech bubble faded out - will that also happen? it's a nice effect. & the longer the amount of text, the longer the bubble stayed before fading. can you do that? :)

**Comment by helenvarley** [comment]
oh and another thing about speech bubbles: they are normally above the avatar, but if your avatar is near the top of the stage so that the bubble wouldn't be visible, it needs to display below the avatar.

**Comment by charlie0605** [comment]
as a base is 3 seconds timeout long enough?

in this case it will be 6 seconds
![image](https://user-images.githubusercontent.com/25602185/40200843-6dde2182-5a71-11e8-83f5-294f0d5f0bb0.png)

In regards to fading I'm not sure if I could do that in canvas @rohrlach do you know if its possible?

**Comment by vickis** [comment]
super great work team :)

**Comment by rohrlach** [comment]
Appears to work.

Some refactoring is needed, But I'm open to putting this in R7-2018 being that this is the final sprint for @charlie0605 

Will wait for someone to test and close (If appropriate)

**Comment by rohrlach** [comment]
Having tried it, I think 5 seconds is still too short.  But we can raise a new issue for upping the delay.

**Comment by vickis** [comment]
agreed :)

**Comment by helenvarley** [comment]
length of time doesn't seem too short, but there is no fade out. the bubble just disappears (in firefox on linux)

**Comment by rohrlach** [comment]
There's no code to make it fade out.

as it stands, making the bubbles fade out will be a performance hit without significant changes to the way frames are rendered.  I have plans to address this, but I think it's unwise to try and shoe-horn it in at this time.

My suggestion is to accept the bubbles as-is for now, and then we add fade later.

**Comment by vickis** [comment]
agreed :)

**Comment by helenvarley** [comment]
ok :)
