### ISSUE TITLE
holding a new avatar without dropping the first one

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/limelight#201]
currently, if you hold a new avatar without dropping the one you were previously holding (i.e. in order to leave it visible on the stage) then that avatar (that hasn't been dropped) becomes inaccessible. it stays visible on the stage, but nobody is able to hold or drop it.

it should be that you can leave one avatar on the stage, hold & operate a different avatar, & that someone else or you can then hold the first avatar.

**Comment by rohrlach** [comment]
Can we have this tested please?

**Comment by helenvarley** [comment]
this seems to work (tested on firefox on linux, on hentest stage where there are 2 avatars - wondering if it would be wise to upload some more avs & test with more??)
(also now getting the bug where the avs i placed on hentest are appearing on test-244 ... will find that issue to add to it)

**Comment by rohrlach** [comment]
Okay - Closing for now.  We can reopen if it comes back.
