### ISSUE TITLE
button to clear unheld avatars

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/limelight#202]
there should be a way to clear all unheld avatars from the stage (as currently exists in UpStage)

**Comment by helenvarley** [comment]
where is the clear button?

**Comment by charlie0605** [comment]
@helenvarley I don't think its available on QA yet

**Comment by charlie0605** [comment]
@helenvarley looks like its on QA now

**Comment by helenvarley** [comment]
great! :) it appears to work (on firefox + linux) BUT we really need to add some more media in order to test it properly. there are only 3 avatars currently on limelight & i think this isn't enough to give us confirmation that clearing is working properly. i'm working intensively until saturday then travelling all day saturday so no time to upload anything myself.
(i still find it really frustrating having to scroll in the tool panels - i know there is an issue for this, maybe i'll bump up its priority!!)

**Comment by rohrlach** [comment]
@helenvarley can we close this issue?

**Comment by helenvarley** [comment]
well i just tested it again & the clear button did not do anything, so no, it appears to be NOT working ... i have only tried on firefox on linux, on the hentest stage where there are only 2 avatars. i will upload some more avatars & try again.

**Comment by helenvarley** [comment]
i added some more avatars & tried it again, & it worked. so ... let's close it for now, & if it proves to be buggy then we can always open a new issue :)
