### ISSUE TITLE
avatar names - changing the name on stage

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/limelight#205]
it should be possible to change an avatar's name on stage. in UpStage this has always been done with a command - which is not very intuitive / easy for newbies. ideally it should be possible to change it in the avatar tool palette by typing in the new name.

**Comment by helenvarley** [comment]
i'm not able to access limelight-qa at all - i get the message "We're sorry, but something went wrong.
If you are the application owner check the logs for more information." (tried in firefox & chrome). it was like this yesterday as well.

**Comment by helenvarley** [comment]
this works, in that i can change the name in the avatar palette & it appears on the stage. however, when my avatar speaks, it shows my player name, not the name of the avatar, in the chat window.
also: it's no good having to scroll down in the avatar palette to do this. the palette needs to take more space from the chat window (to sit over the top of it). scrolling is no good when we are performing & need to do things quickly.
the button says "edit" but maybe should say "save", since you've already edited the name & clicking the button saves it.

**Comment by charlie0605** [comment]
in regards to "scrolling is no good when we are performing & need to do things quickly" does this get done in this issue or #295 ?

**Comment by rohrlach** [comment]
I assume #295 

@helenvarley do you agree?

**Comment by helenvarley** [comment]
works for me - only tested on firefox on linux :)

**Comment by rohrlach** [comment]
I too, think this is working as expected.
