### ISSUE TITLE
workshop - media list: sortable

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/limelight#209]
the media list in the workshop should be sortable by all of the columns.

**Comment by blankgaming** [comment]
Hi Paul, @rohrlach 
Im not sure if i was on the right path, please give me some feedback on what i have done.
![medialist](https://user-images.githubusercontent.com/22442427/28654572-80ffaf9e-72e9-11e7-8ad0-9522659ba7c3.png)


![media_controller](https://user-images.githubusercontent.com/22442427/28654655-2615c70c-72ea-11e7-94b0-d3a17ebb52f9.png)

As you can see, I tried switching the Tags and Actions places to test if it would work but it doesnt. 



![media_helper](https://user-images.githubusercontent.com/22442427/28654677-4b75e13a-72ea-11e7-893c-b0ce1782d855.png)

**Comment by rohrlach** [comment]
@blankgaming you're over-complicating it.

Basically, you need to make the column names clickable and sort the table rows based on the column that is clicked.

You should do this purely in the browser (ie: no ruby code involved)  Search the web for examples of how this is done and choose the solution you think works best.

**Comment by vickis** [comment]
shite sorry 
i went to test this and for some reason my login is not working

and unfortunately neither is forgotten password link (arohamai team its a bit of a default sometimes :)

**Comment by rohrlach** [comment]
Do we have an open issue for that @vickis?

**Comment by helenvarley** [comment]
doesn't work.

**Comment by rohrlach** [comment]
Actually that's a server problem - sometimes you actually have to restart the instance, sometimes you don't ¯\_(ツ)_/¯

Looks good @blankgaming

**Comment by vickis** [comment]
yes working well - super! :)

**Comment by helenvarley** [comment]
tested on limelight & limelight-qa, working on both :)
