### ISSUE TITLE
backdrops - upload media item as a backdrop

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/limelight#212]
players can upload images as backdrops - jpgs, gifs, animations, etc.

**Comment by rohrlach** [comment]
@charlie0605 don't move issue cards into 'Testing' until the PR is merged.

Testing refers to 'Deployed to QA server'

**Comment by charlie0605** [comment]
Ok, sorry about that

**Comment by vickis** [comment]
no option to upload backdrops available
![screen shot 2017-09-12 at 3 12 54 pm](https://user-images.githubusercontent.com/4249450/30306559-f452ce74-97cc-11e7-8c82-6cf5486e2f04.png)

**Comment by rohrlach** [comment]
Update script only runs on the hour ;)

**Comment by charlie0605** [comment]
@rohrlach how come the dropdown menu went back to the previous dropdown menu?

**Comment by helenvarley** [comment]
upload is working.
