### ISSUE TITLE
backdrops - players can select and change backdrops on stages

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/limelight#214]
players can see a backdrops tool palette in which they can click on a backdrop's icon and it then appears on the stage. clicking again on the icon should remove the back drop from the stage, or clicking on another icon replaces it with a new backdrop.

**Comment by thongteav** [comment]
Target layout, for reference:
![image](https://user-images.githubusercontent.com/26214298/30516929-77b6403e-9ba1-11e7-877a-a7ed533bc0e9.png)

**Comment by helenvarley** [comment]
works for me :)
altho i don't see icons for the backdrops, only names; icons make selection much easier. & we definitely need to see more than 3 at a time - often we can have as many as 10 backdrops (or more) on a stage, & if we have to scroll all the time it takes longer to find & change backdrops.

**Comment by helenvarley** [comment]
it doesn't always work immediately - sometimes i click on a backdrop name & nothing happens, i have to click 2-3 times before it appears.

**Comment by rohrlach** [comment]
@thongteav or @charlie0605 - Can you comment on Helen's feedback?

**Comment by thongteav** [comment]
Hi @helenvarley, we could try 4 items at once, but I think anything more than that would make the images really small as the palette isn't really that wide as the one on current upstage website. As for when images are not showing, I think it might have to do with the screen resolution. The team will investigate on that today.

**Comment by thongteav** [comment]
We figured out why the images aren't showing. Prior to this, we didn't create a thumbnail version of the images uploaded for the backdrops. I think you're using backdrops created a while ago, so when the toolbox is looking for the thumbnail it won't find any and will just display the name instead. 

Therefore, you might have to remove all the backdrops existed and then re-uplpad them. It should show the images after that and the clicking should also be more responsive.

**Comment by helenvarley** [comment]
i deleted the backdrops & reuploaded them, & reassigned them to the hentest stage. now i see the thumbnails in the palette. however:
- i can scroll endlessly left or right, & see the 3 backdrop icons repeated over & over again; this is confusing!
- clicking on the icons doesn't seem to work at all, altho once a backdrop did appear on the stage. but now clicking does nothing

as you can see from these screenshots, in UpStage we can currently see 8 backdrop icons without scrolling. the icons are quite a bit smaller than the ones in limelight, but still large enough to be able to select the one you want. there is a rollover with the name of the backdrop, so that if there are 2 that are similar you can see which one you want. 
the space available in the limelight palette is actually bigger than the backdrop bar in UpStage - it's pretty much the same width, & it's higher.
if it's really a problem to fit more than 4 icons there, we can have them in 2 rows; we have said that it's fine for the palettes to cover more of the chat window if they need to (in fact my mock-ups take up a lot more space).
![screenshot at 2017-09-27 16 55 06](https://user-images.githubusercontent.com/3437324/30920694-ea0c916e-a3a4-11e7-84cb-1a47eb701f34.png)
![screenshot at 2017-09-27 16 55 00](https://user-images.githubusercontent.com/3437324/30920695-ea1511f4-a3a4-11e7-95b5-b2d4d3abf8b7.png)

**Comment by thongteav** [comment]
Hi @helenvarley, the team will investigate on that matter and we'll get back to you shortly.

**Comment by charlie0605** [comment]
Hi @helenvarley @vickis 
Could you guys please test this issue again, new code was uploaded #259

**Comment by helenvarley** [comment]
hi guys, this is looking a lot better :) but the icons can still be smaller. you can see from my screengrabs that one icon is hanging out over the chat - not really a problem, but if the icons were smaller it would fit better. also we are still only seeing 4 at a time, & i'd really like to see at least 6.
![screenshot at 2017-10-02 12 57 14](https://user-images.githubusercontent.com/3437324/31074583-9d3cc64e-a771-11e7-88af-f1a456ff43b1.png)
![screenshot at 2017-10-02 12 51 35](https://user-images.githubusercontent.com/3437324/31074582-9d39ad24-a771-11e7-8a37-4e518a51b675.png)

**Comment by charlie0605** [comment]
Hi @helenvarley do you prefer the dot to be smaller or to be just removed as there is an alternative way of navigating the backdrops by clicking on the arrows.
With 6 backdrops at the same time, the backdrops size will be quite small
![image](https://user-images.githubusercontent.com/25602185/31074876-36864714-a7cf-11e7-9f4b-643aba7d6b30.png)

**Comment by helenvarley** [comment]
@charlie0605 the dot confused me at first, because i only had 3 backdrops & i didn't get what it was for. but then once i added 2 more backdrops & understood what it was about, i think it's actually quite good - as it means you have an idea of how many more backdrops there are, & also to click from one dot to the other is less mouse-movement than going to the arrows at either end (but don't take the arrows away!)
if we are going to have these dots as alternative navigation on the backdrop palette, it would make sense to also have them on the other palettes; there should be as much consistency in the interface as possible.

**Comment by charlie0605** [comment]
@helenvarley could you please test this code again I have updated the code

**Comment by helenvarley** [comment]
great, that's much better :)
it would be good to have rollovers so that the name of the backdrop comes up when you hover over it (but that might be a separate issue ... )

**Comment by rohrlach** [comment]
@helenvarley this can actually be part of this issue 👍 

@charlie0605 go ahead with the change.

**Comment by rohrlach** [comment]
Ignore last comment / label changes (was trying to do two things at once - got confused)
