### ISSUE TITLE
Avatar displayed incorrectly

### ISSUE THREAD

**Issue by blankgaming** [upstage-org/limelight#217]
![screenshot from 2017-07-26 16-44-01](https://user-images.githubusercontent.com/22442427/28605008-ec6a4752-7222-11e7-9fc6-5ece490f773e.png)

after dropping the avatar on stage, it is only displayed on the far top left corner.

**Comment by rohrlach** [comment]
Unable to recreate this issue - @blankgaming can you please make sure you have tested your theory on the live server (which is HEAD on master)

**Comment by blankgaming** [comment]
@rohrlach  my apologies Paul, wont happen again.
 I encountered this problem when using the university Upstage workstation so I thought it was an issue because I got the files from the master branch. I didnt encounter this bug when I am using my personal computer.

**Comment by rohrlach** [comment]
No worries - Best to confirm using the QA instance from now on.
