### ISSUE TITLE
Make Panel Titles White

### ISSUE THREAD

**Issue by rohrlach** [upstage-org/limelight#220]
It is my view, that the various panels should have white titles rather than black (as they currently are) and instead turn black on mouse over to indicate that they are clickable (if they are):

![image](https://user-images.githubusercontent.com/2830313/28723707-9771c568-7385-11e7-8c23-c200fc710d87.png)

to:

![image](https://user-images.githubusercontent.com/2830313/28723739-b7b91efc-7385-11e7-9214-937f40d06625.png)

**Comment by helenvarley** [comment]
agree - white is more readable (to me anyway!) :)

**Comment by vickis** [comment]
yep white is good :)

**Comment by helenvarley** [comment]
where should we be seeing this? on both https://limelight-qa.upstage.org.nz/ and https://limelight.upstage.org.nz/, i'm still seeing black panel titles (yes i cleared the cache :) )

**Comment by vickis** [comment]
possibly still needs to be merge and updated? :)

**Comment by rohrlach** [comment]
Yes - my update script broke.. Should be fine now.

**Comment by rohrlach** [comment]
Just kidding - QA is dead.

Will fix tomorrow.

**Comment by helenvarley** [comment]
hehe - i never had the chance to do a thumbs down before!!

**Comment by rohrlach** [comment]
In case anyone missed it - this is up-and-running again.

**Comment by helenvarley** [comment]
i tried to test this on limelight-qa, but there's no media there yet & i'm unable to upload, so i can't see any panel titles to see what colour they are ...

**Comment by rohrlach** [comment]
On the main page? Or the login screen?

**Comment by vickis** [comment]
it is white in the panels titles on https://limelight-qa.upstage.org.nz/ :)
thanks looks great

**Comment by helenvarley** [comment]
ah ok good :)
