### ISSUE TITLE
assign multiple media items to stage

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/limelight#228]
when you are in the stage edit interface, & want to assign multiple media items, it should be possible to select multiple items from the dropdown media list by holding down the shift key.
(we quite often need to assign multiple media items to a stage at the same time, & it's just a bit tedious to have to repeat the process when it should be possible to select multiple items).

**Comment by thongteav** [comment]
I think this is very similar to #173, isn't it?

**Comment by helenvarley** [comment]
indeed, you're right again! clearly i got a bit excited about adding new issues ;)
