### ISSUE TITLE
stages page: "enter" & "edit"

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/limelight#230]
the stages page should have a list of stage names with two options for each: "enter" & "edit".
(the delete button should be on the stage edit screen)

**Comment by francis-villaflor** [comment]
Hi, just to gain confirmation, would the 'Delete' button still be located next to the 'Enter' & 'Edit' buttons? Or would the Stage Names in the Stages page only have the 'Enter' and 'Edit' buttons, where the 'Delete' button can be accessed once you click the 'Edit' button that leads to the stage edit screen?

Thanks
-Francis

**Comment by vickis** [comment]
Yes the second option
the delete button should *never* be able to be clicked by mistake (as in
rushing into a stage last minute ;)

so having it safely tucked away on the edit page would be great!

we used to have a red reload button that we tried to caution players not to
click ...  ;)

**Comment by helenvarley** [comment]
this is great. i just have a general comment about the layout of the screens in general - but i'll make that into a new issue :)
