### ISSUE TITLE
Adding media's drop menu

### ISSUE THREAD

**Issue by charlie0605** [upstage-org/limelight#231]
Drop down menu is not shown properly, it is in a single line. Can only see avatar, and part of sound.

**Comment by rohrlach** [comment]
@charlie0605 please provide a screenshot

**Comment by charlie0605** [comment]
![image](https://user-images.githubusercontent.com/25602185/30008888-ab33c49c-9177-11e7-83ad-d3994787b5de.png)

**Comment by rohrlach** [comment]
@charlie0605 please provide a screenshot of your fix in PR #232

**Comment by helenvarley** [comment]
it's not clear to me which dropdown menu i should be looking at. if it's the one at the right hand side on https://limelight-qa.upstage.org.nz/media for adding media, this is not showing as a dropdown for me. the options go off to the right, i only see "Avatar S" & it's not possible to scroll to the right. 
![screenshot at 2017-09-04 10 48 45](https://user-images.githubusercontent.com/3437324/30018851-c3eb313c-915e-11e7-917c-f90b1468ba03.png)

**Comment by charlie0605** [comment]
![image](https://user-images.githubusercontent.com/25602185/30019168-b4e068b0-91b3-11e7-8168-56a6f1dfcf46.png)

**Comment by charlie0605** [comment]
@helenvarley thats the dropdown menu im talking about, I tested on the main limelight website it seem to be working fine, not sure why its not working on the qa website

**Comment by rohrlach** [comment]
Fix confirmed on QA

![screen shot 2017-09-06 at 11 31 11 am](https://user-images.githubusercontent.com/2830313/30120733-b89578e8-92f7-11e7-94ab-818403a30a8f.png)
