### ISSUE TITLE
Unit Tests for Models

### ISSUE THREAD

**Issue by rohrlach** [upstage-org/limelight#235]
This ticket requires that all models have at least two unit tests for each attribute or method:

1) Ensure correct input is accepted
2) Ensure bad input is rejected.

**Comment by thongteav** [comment]
Hi Paul, by 'all models', do you mean including the existing models? Or just the models we've created for our issues?

**Comment by rohrlach** [comment]
All of them.

**Comment by thongteav** [comment]
Ok.

**Comment by rohrlach** [comment]
I eventually want to put CI/CD in place - But there's not much point in doing that until we have some tests to automate.

I understand that this is dull work - But it'll save you a lot of bugs to fix down the line.

**Comment by rohrlach** [comment]
It's worth noting that each team member can do a model each and submit their own PRs.  Once the 2017 guys are caught up I'll be putting them on these as well.

**Comment by rohrlach** [comment]
No clear acceptance criteria and is now mandated
