### ISSUE TITLE
email confirmation message persists on limelight-qa

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/limelight#238]
every time i go to https://limelight-qa.upstage.org.nz/, i get the message: "Thank you, your email address has been confirmed" at the top of the foyer interface. 
(i don't get this message on https://limelight.upstage.org.nz/)
![screenshot at 2017-09-12 10 50 20](https://user-images.githubusercontent.com/3437324/30316718-5bd31a6a-97a8-11e7-953d-6dccdd5ecbdc.png)

**Comment by rohrlach** [comment]
@helenvarley can you try closing the message box, doing a hard refresh and logging out/back in.

Cannot recreate this (Chrome/macOS)

**Comment by helenvarley** [comment]
that got rid of it :)
can it be set so that this message only appears once?

**Comment by rohrlach** [comment]
It's supposed to only show once - my theory is that your browser did something strange with it's cache. Being QA it might have been due to timing with an update.

Closing this for now.
