### ISSUE TITLE
stage accessibility on foyer page

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/limelight#240]
it should be possible to see your access to stages in the stage list on the foyer page.

- audience members should only see the stages that are publicly accessible
- logged in players should see an additional column, like the ones showing the player & audience numbers, that indicates their personal access to each stage, e.g. audience, player, owner

**Comment by rohrlach** [comment]
@helenvarley we don't currently have a concept of stages that aren't publicly accessible.  I suggest you either raise this as an issue too and remove from this one until it's in place.

**Comment by rohrlach** [comment]
Also - To be clear - You want the player/audience count to only be visible to players?

**Comment by helenvarley** [comment]
sorry, i wasn't clear; public should also be able to see player/audience numbers. but they shouldn't see a column that indicates accessibility, because they should only see the stages they can enter & they are not logged in so only entering as public.
i'll raise a separate issue for non-public stages.

**Comment by thongteav** [comment]
Hi @rohrlach, there's no implementation to say if a logged in user is an audience or player yet since the stage only contains an owner. Would that be a separate issue?

**Comment by rohrlach** [comment]
@thongteav assume that logged in users are 'Players' and anonymous users are 'audience'

**Comment by thongteav** [comment]
@helenvarley @vickis @rohrlach I noticed that the headings for 'name', 'players', 'audience' are using extra thin font. Is this desirable? 
![image](https://user-images.githubusercontent.com/26214298/31314068-f2a9b9a8-ac52-11e7-8b4f-7ca04a64f5e9.png)

**Comment by helenvarley** [comment]
this might be in order to make the word "Audience" fit into a certain width - i don't know the reason; for me it is readable so it's fine, i would just say that there should be consistency with fonts elsewhere, but this is a sort of subheading & i can't find a comparable other instance.

it has made me notice that the numbers under plays & audience are left aligned. i would prefer if they were either centred or right aligned.

**Comment by thongteav** [comment]
@helenvarley would this be alright?
![image](https://user-images.githubusercontent.com/26214298/31315718-9aa8fcaa-ac7a-11e7-9be3-8be0c9218402.png)

**Comment by helenvarley** [comment]
yes :)

**Comment by thongteav** [comment]
This can be tested as well.

**Comment by helenvarley** [comment]
looks good :)
