### ISSUE TITLE
media item - show assigned to stage in media list

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/limelight#245]
https://limelight-qa.upstage.org.nz/media has a column for "stages" in the media list; this column should list the stages to which each media item is assigned (& the stage names should be clickable links which will take you to the edit screen for that stage).
the stages should be alphabeticalised.

**Comment by helenvarley** [comment]
works in firefox on linux :)

**Comment by rohrlach** [comment]
works for Chrome under Windows and macOS
