### ISSUE TITLE
HTTP/422 When Attempting to Assign Existing Tag to Stage

### ISSUE THREAD

**Issue by rohrlach** [upstage-org/limelight#250]
![image](https://user-images.githubusercontent.com/2830313/30777313-c0641afc-a085-11e7-9a5b-6dbf544a361c.png)

![image](https://user-images.githubusercontent.com/2830313/30777318-ccc16926-a085-11e7-82a3-9c1ecaac0425.png)

![image](https://user-images.githubusercontent.com/2830313/30777327-0a13d854-a086-11e7-9b48-738a0db69add.png)

**Comment by thongteav** [comment]
Hi @rohrlach, is there a certain way to replicate this bug? 

This is what I have when doing it:
![image](https://user-images.githubusercontent.com/26214298/30777855-3c25307c-a121-11e7-944c-48cd35bc48e8.png)

**Comment by thongteav** [comment]
Oh I got it, if you have more than 1 word for the tag, this bug will show up.

**Comment by rohrlach** [comment]
Okay.  This isn't the expected behavior.  The system should be able to handle that.

**Comment by charlie0605** [comment]
Hi @rohrlach, it seems like when trying to find new tag the error arises. In the controller create method. @tag = Tag.find_by_name(params[:tag][:name]), this line, the params is not formated before it asks if the tag is existed in the database. I've added .strip.downcase.gsub(/[^a-z0-9\s\-]/, '').gsub(/\s/, '-') at then end and it allowed adding existing tag with space to persective but when there is empty name it still give HTTP 422 error, so i check before it tries to find it from the database if the param is empty. Do you have any suggestions on how I could go about doing this?

**Comment by rohrlach** [comment]
@charlie0605 I believe your diagnosis to be correct (Having looked at the code) You'll notice that the ```Tag``` model has a single validation instruction that makes sure the name conforms and is unique:

```validates :name, :presence => true, :uniqueness => true, :format => /[a-z0-9\-]/, :length => { maximum: 25 }```

You'll also notice that the name is "standardized" before validations are run:

```before_validation :standardize_name```

What I suggest, is that you re-implement the ```create``` action such that it utilizes this workflow.  Consider the following:
- Create a new object with the given parameters
- Check if it's valid
- If yes
  - This must be a new tag
  - Create the tag
- If no, we can assume that it's because the tag exists
  - Fetch the existing tag
  - Use that instead

**Comment by rohrlach** [comment]
Also worth noting: it'd be good to write some tests for this once you've fixed the issue

**Comment by thongteav** [comment]
This should address bug #172 upon completion.

**Comment by charlie0605** [comment]
@rohrlach How would I go about testing when the tag name is empty. I have got some test up. Now I'm trying to test when the tag name is empty on stage. How would I simulate when the player is on the stage page and clicked on add tag and it renders the form, then they enter an empty name. I'm trying to test for the presence of flash[:danger]

**Comment by vickis** [comment]
Ha ha i got a visual of 'flash  gordon' 
:)

**Comment by rohrlach** [comment]
@charlie0605 can you provide the spec you have thus far?

**Comment by charlie0605** [comment]
@rohrlach I have committed the code in issue#250 branch

**Comment by rohrlach** [comment]
Does what you're currently doing not work?

**Comment by charlie0605** [comment]
No, the flash[:danger] is nil
![image](https://user-images.githubusercontent.com/25602185/31406204-02dd0ddc-ae5d-11e7-8aa1-0c5fab19f0f5.png)

**Comment by rohrlach** [comment]
Ahh - It's probably because whilst you are using a spec file for the controller, you are only actually dealing with models.

You need to be testing ```TagsController``` and ```StagesController``` not ```Stage``` and ```Tag```

**Comment by rohrlach** [comment]
@thongteav I've also added you as someone who can test this in QA

**Comment by thongteav** [comment]
Hi @rohrlach, do I just log in to https://limelight-qa.upstage.org.nz/login with same login as limelight upstage?

**Comment by helenvarley** [comment]
not quite sure what i'm meant to test here, but i did the following:
- went to the edit interface for the hentest stage & added the tag "test"
- went to media, created a tag "helen" on an avatar, then went to the edit interface for the hentest stage & added the tag "helen" to this stage. i typed h in the input field & "helen" appeared as a dropdown so i selected it. 

i see that there is now a "tags" link in the navigation, & when i click on this i get a list of tags, but clicking on a tag in this list does not then present me with a list of media items & stages that have this tag - which is what i expected to happen. (new issue?)

**Comment by charlie0605** [comment]
@helenvarley are you referring to #210 ?

**Comment by helenvarley** [comment]
yes, thank you! :)

**Comment by charlie0605** [comment]
This issue is mainly to do with when you add duplicate tags with space in the tag name. The second time you add it the console should not get an HTTP 422 error. It should redirect you back to the page you were on ie stage if you were trying to add tag to the stage

**Comment by helenvarley** [comment]
ok - i'm not really sure how to test that. i didn't get any errors.

**Comment by rohrlach** [comment]
@thongteav No, you'll need to create another account - The envs are isolated.

**Comment by thongteav** [comment]
Ok, I've created the account. Waiting for it to get activated.

**Comment by rohrlach** [comment]
Done

**Comment by thongteav** [comment]
Testing procedure:
- creating new tag for 'test 2'
- creating another tag with 'test 2'
- creating another one with 'test-2'
- unassigned the tag

Result: No http/422 error found.
Tested on: Google chrome, Microsoft edge, Firefox on windows.
![image](https://user-images.githubusercontent.com/26214298/31866468-57c94bf2-b7dc-11e7-9611-4f65bc988e87.png)

![image](https://user-images.githubusercontent.com/26214298/31866461-3ce20900-b7dc-11e7-8787-73dcc509ffb3.png)

![image](https://user-images.githubusercontent.com/26214298/31866469-5d3aae14-b7dc-11e7-8311-0e34f31877a6.png)

**Comment by thongteav** [comment]
@rohrlach So is this fine?
