### ISSUE TITLE
delete media message

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/limelight#254]
i am deleting backdrops, & when i click on the delete icon i get a pop-up message that says "(name of media" will be removed" * cancel or ok buttons.

it would be good to include the media type in this pop-up message, as there could be multiple media items with the same or similar names, such as a backdrop called "trees" and an avatar called "tree"; so it would be helpful if the pop-up message said "The backdrop "Trees" will be removed" or "The avatar "Tree" will be removed"

**Comment by thongteav** [comment]
Hi @rohrlach, should we use a variable like: @backdrop.class.name.demodulize or a simple hard code 'backdrop' would be enough?

**Comment by rohrlach** [comment]
@thongteav this is one of the few times I recommend hard-coding.  This is because to the user, they are removing a backdrop - But the classes we use to implement the backdrop functionality don't necessarily have to be called as such.

**Comment by helenvarley** [comment]
great, thanks :)

(btw, in the dialogue box, i also got the message "Prevent this page from creating additional dialogues" & a checkbox - see screengrab. is that something my browser is putting in? if it's something limelight is generating, i don't think it's appropriate/necessary)
![screenshot at 2017-10-06 10 54 10](https://user-images.githubusercontent.com/3437324/31270523-015d040c-aa85-11e7-8c5f-ea3a4ca234c5.png)

**Comment by thongteav** [comment]
@helenvarley it seems like it's a built-in feature in the web browsers when the pop up appears too frequently. I'll have a look if there's any way to disable or prevent it from showing.

**Comment by rohrlach** [comment]
There isn't a way to turn this off.

One thing we could do is use a Bootstrap modal rather than a ```confirm```

**Comment by helenvarley** [comment]
interesting. it's not a big deal, but it's slightly confusing to have irrelevant info there, & what would happen if someone ticked the box to not be shown additional dialogues? would that stop other dialogue boxes from opening?
in the current Upstage we don't see it, e.g.:
![screenshot at 2017-10-06 16 23 46](https://user-images.githubusercontent.com/3437324/31282490-00a613c2-aab3-11e7-9728-6f21775ab773.png)

**Comment by rohrlach** [comment]
Yes it would.  The one that's been provided is a browser (built in) dialog.  The legacy system uses a custom overlay (Which would be Bootstrap in Limelight's case)

**Comment by helenvarley** [comment]
i think we do need to do something to avoid this message appearing. there's a definite risk for newbies to tick the box, & i guess that would mean that if they accidentally clicked on a delete button, the media would be immediately deleted without this checking step. since they can remove media other than their own, i think it's really important to ensure that this checking step always happens & isn't possible to accidentally stop.

**Comment by vickis** [comment]
Agree - is important that media is not deleted accidentally so a
Check step essential - thanks :)

**Comment by thongteav** [comment]
Hi all, this should be up for testing again. Please test it out.

**Comment by helenvarley** [comment]
great, that's much better :)
but before we close it, i'd like to suggest a slight change in the wording. at the moment it says:

"The avatar "helen" will be removed?"

but it would be nicer if it said:

"Are you sure you want to delete the avatar "helen"?"

using the word "delete" rather than "remove" makes it more clear that it's going to be deleted from the server, since media can be assigned to a stage & then unassigned, or removed, from that stage. so it might not be clear to people that it's really being deleted.

there could even be a sub-line that says "It will be deleted from the server and no longer available on any stages that it was assigned to" (for media items).

**Comment by thongteav** [comment]
hi @helenvarley, please have a look at these different combos:
Option 1:
![image](https://user-images.githubusercontent.com/26214298/31709325-284bfe6a-b44e-11e7-9f0b-03231cd2c01d.png)
Option 2:
![image](https://user-images.githubusercontent.com/26214298/31709415-70bad68a-b44e-11e7-9a8f-7cc2cb666c39.png)
Option 3:
![image](https://user-images.githubusercontent.com/26214298/31709477-a870ce4a-b44e-11e7-8a3a-3391bd22e781.png)
Option 4:
![image](https://user-images.githubusercontent.com/26214298/31710957-13083712-b453-11e7-99f6-93a5b026d21d.png)

Does any of these fit? I can still tweak it around a bit, just let me know how you'd like it to look.

**Comment by helenvarley** [comment]
@thongteav - great :)  i think i prefer the ones without "confirmation" at the top - this isn't really necessary. 
pedantically, it would be nice if the "to" could fit onto the same line as the rest of the text - maybe make the font of the second sentence a fraction smaller?

**Comment by rohrlach** [comment]
Having the bold headings is a nice touch

**Comment by rohrlach** [comment]
This is still inconsistent:
![image](https://user-images.githubusercontent.com/2830313/37406369-5c5d5c8e-276d-11e8-929a-436a7cf5b7a4.png)

vs

![image](https://user-images.githubusercontent.com/2830313/37406385-6d58c672-276d-11e8-9feb-46517b06b2c4.png)

**Comment by alexanderglenn** [comment]
I have amended the delete messages. They should follow the format:

Title: "Are you sure want to delete [Type], [Name]?"
Confirm "This [type] will be deleted from the server and no longer be available."

**Comment by helenvarley** [comment]
looks good to me :+1:
