### ISSUE TITLE
media list - finding media

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/limelight#255]
after deleting a backdrop, i was returned to https://limelight-qa.upstage.org.nz/backdrops - a page which shows only backdrop media items.
how do i get to this page apart from after deleting an item?
if we don't have the excellent filter system that we currently have in UpStage (which i would prefer to have!!), then pages like this that have only one media type are going to be essential. also pages that have only one player's media.

**Comment by rohrlach** [comment]
This isn't what's meant to happen.  It's meant to return you to the media index and then we're going to put filters on that page

**Comment by rohrlach** [comment]
**GOAL OF ISSUE:** Upon deletion of a backdrop, return the user to ```/media```

**Comment by thongteav** [comment]
Hi @helenvarley, @rohrlach, does that mean deleting avatars and sounds should redirect the user to /media too? Because they are also redirecting to their own page currently.

**Comment by helenvarley** [comment]
from the media list, i deleted a backdrop & got returned to the media list.
from the edit screen for the backdrop, i deleted it & got returned to the media list.
seems to be how it should work :)
