### ISSUE TITLE
avatar - resize on stage

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/limelight#257]
a player can resize the avatar that they are holding on stage

**Comment by helenvarley** [comment]
using firefox on linux: it works! :) BUT
- with one avatar, it seems to be fine, but with my helen avatar, she is now completely squashed. she wasn't like this yesterday. i don't know if this is because the other av is maybe square & mine is rectangluar? but avatars will come in all dimensions ... so it must always be that the correct proportions are retained.
- a scrollbar on the palette is not a workable solution; it would be better for the palette to cover more of the chat window (see my mockups pdf ... ). when we are operating avatars we need to be moving quickly, we don't have time to scroll here.
- i'm not seeing a rollover name for the avatars - this is another issue, i know, but just mentioning it here for the fun of it ;)

**Comment by thongteav** [comment]
I'm not sure on the requirement of this issue, there are 2 other resizing avatar issues: #304 and #307. The bug on squashing avatar has also been fixed.
So is the goal of this issue is to resize the chat window and tool palette so that there's no need for scrolling?

**Comment by helenvarley** [comment]
@thongteav - yes; probably this issue should be closed & a new one opened that is about removing the scrollbar on the tool palettes. i'll do that :)
