### ISSUE TITLE
same thing happening on 2 different stages

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/limelight#271]
currently on limelight-qa there are 2 stages - hentest  & test244. hentest has 2 avatars assigned to it, test244 has only one.
if i put an avatar on the stage in hentest, it appears on the stage in test244
even if that avatar is not actually assigned to that stage, & not showing up in the avatar palette, it still appears on the stage
stages should function totally independently from each other.

**Comment by rohrlach** [comment]
What're you using?

Unable to reproduce this:
- Chrome on Windows 10 / macOS High Sierra 
- Edge on Windows 10

**Comment by helenvarley** [comment]
firefox 56.0 on linux (ubuntu mate)

**Comment by helenvarley** [comment]
still happening (on firefox / linux)

**Comment by charlie0605** [comment]
Hi @helenvarley,
Can you please check if this issue still exist?
I have checked this on my Mac and I don't see this issue. I've also asked Thong to check it on Ubuntu and he didn't have this problem. Placing one avatar on a stage doesn't show on another stage.

**Comment by helenvarley** [comment]
hi @charlie0605, i just tried having 2 stages open & moving avatars on them, & the stages worked independently (as they should). i also put a backdrop on one & drew on the other, & these things just happened on the one stage, as they should. so it looks like it's fixed :)

**Comment by vickis** [comment]
wahoo!

**Comment by helenvarley** [comment]
i've reopened this because yesterday it happened again. i was demonstrating limelight to an artist colleague (a very cool puppeteer who could so some amazing stuff in UpStage) & i put some media onto the hentest stage to show her. then i went into the other stage (test-244) & discovered that the same media (backdrops and avatars) was displayed there.
this was using firefox on linux.

**Comment by charlie0605** [comment]
@rohrlach I found out that its when you click back on the browser it still stores some types of data from the stage and when you enter another it will have the same state as the previous stage. I tried going back and refreshing the page before entering the second stage and it works perfectly fine. You mentioned that you are working on an issue #197, would this issue that you are working on possibly fix this issue too?

**Comment by rohrlach** [comment]
@charlie0605 - No, regardless of #197 things should only be happening on the stage that they are performed on.

**Comment by helenvarley** [comment]
still happening - just was testing the avatar distortion on hentest stage then went to test-244 to check it there, & found the avatars in the positions i'd put them on hentest. the "sharing" avatar is not even assigned to test-244, but there it is on the stage ...

**Comment by thongteav** [comment]
@helenvarley it hasn't been fixed yet. We'll have a look on this soon.

**Comment by helenvarley** [comment]
happened again today. i was on hentest, placed avatars, used back button to go back to foyer then entered test-244 and found the avatars where i had placed them on the other stage (including one av that is not assigned to that stage).

**Comment by rohrlach** [comment]
Yep - Being that it hasn't been addressed, I expect it to still happen :wink:

**Comment by helenvarley** [comment]
still happening. i went to test-244, & put my helen avatar on the stage (it's the only avatar assigned to this stage). then i went to the hentest stage, no avatars were showing on the stage. i put the sharing avatar on the stage. then i went back to test-244, & found that the sharing avatar is also showing on that stage, even though it is not assigned to that stage.
![screenshot at 2018-05-01 20 14 25](https://user-images.githubusercontent.com/3437324/39486431-60da21c2-4d7c-11e8-8403-12aa268d0424.png)
![screenshot at 2018-05-01 20 14 17](https://user-images.githubusercontent.com/3437324/39486432-6102b632-4d7c-11e8-98dd-e80a5c034707.png)

**Comment by helenvarley** [comment]
when i did shift+reload on test-244, both avatars disappeared. this shouldn't happen - the helen avatar i placed there should stay.

**Comment by helenvarley** [comment]
looks like it's working properly now :+1:

**Comment by vickis** [comment]
super! :)
