### ISSUE TITLE
Unable to work with Avatars Consistently - Edge on Win10

### ISSUE THREAD

**Issue by rohrlach** [upstage-org/limelight#273]
Holding and Placing of Avatars doesn't always work in Edge

**Comment by thongteav** [comment]
@rohrlach, do you mean when you initially drop the avatar onto the stage and it doesn't show the image and just the name?

**Comment by rohrlach** [comment]
Haven't tested with name.  Basically, avatars weren't working in Edge

**Comment by thongteav** [comment]
@rohrlach just making sure that I'm working on the right thing. Some inconsistencies I found regarding the place and hold are: 
1. When a player is placing an avatar for the first time, only the name and not the image is shown for other players and the audience.
2. When a player drops an avatar, only other players get the update. The audience still sees the avatar.

**Comment by rohrlach** [comment]
@thongteav that's correct.

**Comment by rohrlach** [comment]
According to @charlie0605 in #308 this is fixed.

I don't have an Edge capable machine at the moment - Taking his word for it.
