### ISSUE TITLE
Avatar name is hidden behind image

### ISSUE THREAD

**Issue by JoeIceCream** [upstage-org/limelight#274]
There is a bug where the avatar name is not displaying correctly as it is behind the avatar image. The name should be below the image and in the center of it's width.

**Comment by thongteav** [comment]
![image](https://user-images.githubusercontent.com/26214298/37312733-14d83ca6-26b1-11e8-9686-f15eb919a3f6.png)
![image](https://user-images.githubusercontent.com/26214298/37312763-39161fb6-26b1-11e8-95fb-658a436c3e28.png)
![image](https://user-images.githubusercontent.com/26214298/37312808-661415d6-26b1-11e8-8dad-68d5435a3168.png)

I don't seem to have this problem with my testing on main limelight, limelight-qa, and local server on edge, firefox and chrome. 
@rohrlach @helenvarley @vickis do you have this issue?

**Comment by rohrlach** [comment]
I can't recreate this issue either - Closing for now

**Comment by helenvarley** [comment]
i also don't have this problem - but the name is very small ...
