### ISSUE TITLE
Avatar resizing distortion

### ISSUE THREAD

**Issue by JoeIceCream** [upstage-org/limelight#275]
Currently avatar's on canvas are being distorted due to the resize function, avatars should retain their original height to width ratio.

**Comment by helenvarley** [comment]
is this to do with the helen avatar being squashed? i don't know if that is connected to the on-stage scaling or not. but it needs to be fixed!

**Comment by helenvarley** [comment]
great! i'm very happy to be back to my normal proportions :) :+1:
