### ISSUE TITLE
Avatar Instant Resize

### ISSUE THREAD

**Issue by rohrlach** [upstage-org/limelight#307]
**Requires that #304 is closed**

This issue asks that:
- A toggle be placed near the avatar resize slider
- The toggle indicate whether 'Instant' or 'Gradual' resizing is enabled.

Instant resizing:
- Does not send updates to other users until the player has released the slider
- One update is then sent to other users and the avatar resizes 'Instantly'

While using the slider in 'Instant' mode, the player doing the resizing should see a slightly opaque version of their avatar grow and shrink in real time - much like the 'drag-and-drop' avatar movement.  This is so the player has an idea of what the instant resize will look like.

**Comment by vickis** [comment]
i think more likely gradual
as in moving forward in space

the instant might be more likely for scene change...

**Comment by helenvarley** [comment]
i agree. please make gradual be the default setting :)

**Comment by helenvarley** [comment]
very cool :)
