### ISSUE TITLE
MacOS ArgumentError on Ruby 2.5.0

### ISSUE THREAD

**Issue by charlie0605** [upstage-org/limelight#315]
After updating the Ruby to 2.5.0 I get an ArgumentError.
As soon as I start the rails server and access the website there is ArgumentError
![image](https://user-images.githubusercontent.com/25602185/37869882-8361ef3c-3025-11e8-815c-aa6f4dd8a3ab.png)

The first error got 4 sometimes 2 arguments but expects 0. After that the arguments given was larger
![image](https://user-images.githubusercontent.com/25602185/37869895-d6fa86ea-3025-11e8-80cb-f59c23265525.png)

**Comment by rohrlach** [comment]
Fairly certain this is unique to MacOS

**Comment by rohrlach** [comment]
Awaiting #316
