### ISSUE TITLE
Styling inconsistencies

### ISSUE THREAD

**Issue by rohrlach** [upstage-org/limelight#32]
![screen shot 2017-04-12 at 1 40 06 pm](https://cloud.githubusercontent.com/assets/2830313/24971910/9370fe68-1f87-11e7-8c63-ca8a8ac73fe3.png)
![screen shot 2017-04-12 at 1 40 15 pm](https://cloud.githubusercontent.com/assets/2830313/24971911/93755300-1f87-11e7-8476-581290d46ef4.png)

Styles that apply to the performance screen should not override those elsewhere.

Chrome 57 on macOS Sierra

**Comment by blankgaming** [comment]
Hi Paul, 
I had tried to fix the style inconsistencies but sadly couldnt solve it yet, asked Jason for help also but he also couldnt figure out how to solve it yet.  We were using these following links and others to help get to [it.]
(http://stackoverflow.com/questions/14694720/referencing-different-stylesheets-in-different-views-in-rails)
[c](http://stackoverflow.com/questions/19304681/activeadmin-overrides-my-css)
[s](https://github.com/activeadmin/activeadmin/issues/825)
[s](http://www.mattboldt.com/organizing-css-and-sass-rails/)

**Comment by blankgaming** [comment]
![performance](https://cloud.githubusercontent.com/assets/22442427/26037517/6c0e57be-3948-11e7-8749-6c51fbe4639f.png)

**Comment by rohrlach** [comment]
Hey @blankgaming ,

Sure - It's actually theatre.scss at line 55 the selector needs to be more specific:
```
div#chat > div.panel-footer {
```
Meaning: any div elements with the 'panel-footer' class that are found as direct child elements of a div element with the id 'chat'

Rather than just:
```
.panel-footer {
```

**Comment by rohrlach** [comment]
More in-depth information can be found here: https://www.w3schools.com/cssref/css_selectors.asp

**Comment by blankgaming** [comment]
@rohrlach 
Thanks Paul,

Me and Jason tried approaching this method before, which was at performance.html.erb:
<div class="**panel-footer.green**">
                        <% unless current_user.nil? %>
                          <div class="input-group">
                            <% Message::MODIFIERS.each do |k, v| %>
                              <%= label_tag do %>
                                <%= check_box_tag "#{k.to_s}Toggle"....
and at theatre.scss:
.panel-footer{
  width: 100%;
    height: 5vh;
    border: 1px solid YellowGreen;
}
changed to
.panel-footer.green{
  width: 100%;
    height: 5vh;
    border: 1px solid YellowGreen;
}

**Comment by blankgaming** [comment]
![nocolor](https://cloud.githubusercontent.com/assets/22442427/26051339/012dfe40-39b6-11e7-8abf-3f5480e1763f.png)
![virtualbox_2017-05-15_21-33-30](https://cloud.githubusercontent.com/assets/22442427/26051376/1913a38e-39b6-11e7-804b-5dda105a4e57.png)

**Comment by rohrlach** [comment]
@blankgaming The reason your approach didn't work is that in HTML you are specifying ```class="panel-footer.green``` literally.  But in CSS, ```panel-footer.green {``` actually refers to an element that has both the ```panel-footer``` and ```green``` classes. IE: ```class="panel-footer green"```

**Comment by rohrlach** [comment]
Code provided by @blankgaming meets the criteria of this issue - Thus, closing.
