### ISSUE TITLE
hierarchy of palettes

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/limelight#323]
in the on-stage tools, the avatar palette should be the default palette, i.e. when you first enter a stage as a player that is the palette that is visible. its tab should be the first one on the left at the top. 

i'm not sure what order the rest of them should be in, just that the avatar palette should be default. (maybe @vickis has an opinion about what should come next ... we could also ask others, to try to determine what is most used).

**Comment by rohrlach** [comment]
Marking as a bug - Because that's how it was originally designed to be.

**Comment by vickis** [comment]
it should privilege the avatar tab yes

then next could be audio then drawing (nicely alphabetical

unless you call it drawing and sound....)
really no preference but agree default is drawing :)

**Comment by helenvarley** [comment]
@vickis i hope you meant you agree the default is avatar ;)

so let's go alphabetical for now, which would be:
avatars
audio
backdrops
drawing
streams (assuming the streaming is going to work separately from avatars?)

(in my mock-up for the tool-palettes i also have Props, but we need to have more discussion about whether or not we need that, & Online, for pulling media directly from online sources; as well as a tab for private (player) chat. i guess these all need their own issues for further down the line.)

**Comment by vickis** [comment]
well of course ;)

**Comment by helenvarley** [comment]
great :+1:

**Comment by vickis** [comment]
super thanks! :)
