### ISSUE TITLE
Suggestion of Duplicate Media Assignment

### ISSUE THREAD

**Issue by rohrlach** [upstage-org/limelight#44]
User should not be given the option to assign media to a stage if it has already been assigned

![screen shot 2017-04-15 at 7 37 56 pm](https://cloud.githubusercontent.com/assets/2830313/25067491/5097365a-2213-11e7-875c-a4131575a1bb.png)

**Comment by JoeIceCream** [comment]
Hi Paul, I've been wanting to do some testing on this whilst running the UpStage website so that I could attempt to get the same outcome as the screenshot you've provided. Do you have any suggestions as to what media I could use? Or do we have some media already that I'm not aware of?

**Comment by rohrlach** [comment]
@JoeIceCream The media itself doesn't matter - You can test with whatever you like - The issue is that the dropdown is not filtering out media that is already assigned to the stage.

**Comment by JoeIceCream** [comment]
Ok thanks Paul, I'll see what media I can find to test it.

**Comment by rohrlach** [comment]
@JoeIceCream This ticket is actually outdated - Can you please look at #119 instead?
