### ISSUE TITLE
Suggestion of Duplicate Avatar Assignment

### ISSUE THREAD

**Issue by rohrlach** [upstage-org/limelight#45]
User should not be given the option to assign an avatar to a stage if it has already been assigned

![screen shot 2017-04-15 at 7 38 51 pm](https://cloud.githubusercontent.com/assets/2830313/25067497/97c74c40-2213-11e7-87b3-69372fa5e48b.png)

**Comment by helenvarley** [comment]
i guess you are working on this still, as i can't access the stage edit interface (i get the "something went wrong" message). & on avatar edit interface there is no option for assigning to a stage.

**Comment by rohrlach** [comment]
No, no - I forgot to take out some debugging code.  The debugger doesn't get installed on the server so it fails.

Should work now

**Comment by thongteav** [comment]
I think this has been addressed right?
