### ISSUE TITLE
Performance Space does not make good use of the screen

### ISSUE THREAD

**Issue by rohrlach** [upstage-org/limelight#6]
- [ ] The performance space should look as close to the existing performance space as possible:

![image](https://cloud.githubusercontent.com/assets/2830313/22485918/70cef610-e7d5-11e6-9df9-15fd7ea9e8ae.png)

**Comment by rohrlach** [comment]
@Tawpin I don't think the chat/controls panel is meant to overlap the stage

![screen shot 2017-04-11 at 9 19 27 pm](https://cloud.githubusercontent.com/assets/2830313/24937137/9d239532-1efc-11e7-9e40-3fecabf149ef.png)

**Comment by vickis** [comment]
the drawing palette looks clear but does the colour only have that limited range of options?
and yes the chat/palettes if movable need to still allow for a clear stage space (where the action is!)

**Comment by rohrlach** [comment]
For now, the colour range is okay.

I want the performance space to have all the features in it before I ramp up the number of options for each feature.

**Comment by helenvarley** [comment]
does this mean that there won't be the same layer concept in the drawing palette? instead a number of "pens" that can draw in a single layer? how to make a "curtain" of drawing at the front of everything, or a background drawing behind avatars? can multiple players draw at the same time?
(i guess these things probably should be a separate drawing palette issue??)

**Comment by rohrlach** [comment]
I assume that multiple players can draw at the same time but there's no concept of layers at this point. This should be a separate issue.

**Comment by vickis** [comment]
Ah ok all good :)

**Comment by rohrlach** [comment]
My mistake - I noticed that my deploy script was out-of-date.

![screen shot 2017-04-14 at 3 49 25 pm](https://cloud.githubusercontent.com/assets/2830313/25054252/0bcc378a-212a-11e7-8aed-4b7aa46da475.png)
