### ISSUE TITLE
Tag/Media Assignment

### ISSUE THREAD

**Issue by rohrlach** [upstage-org/limelight#61]
Relates to #59 

- Tags should be assignable to Medium objects in a many-to-many relationship
- Association resource to be created
- Association is destroyed on destruction of either the Medium object or the Tag object

**Comment by rohrlach** [comment]
Scheduled for deployment in half an hour

**Comment by helenvarley** [comment]
not sure how to test this? i don't see tags anywhere ...

**Comment by rohrlach** [comment]
@helenvarley deploy failed... See #69  Where Rails screwed us over in their latest update

**Comment by helenvarley** [comment]
ah ok. i will look again tomorrow then :) have fun!

**Comment by rohrlach** [comment]
#69 resolved and this this can now be tested

**Comment by helenvarley** [comment]
tested & it works - able to add & remove tags. tag suggestions (previously used tags) appear in a dropdown which is helpful as it should help to reduce multiple similar tags being created.

now all we need is a way to sort media by tag ... i assume that's coming :)

**Comment by rohrlach** [comment]
@helenvarley Yes - #82 :)
