### ISSUE TITLE
Tag/Stage Assignment

### ISSUE THREAD

**Issue by rohrlach** [upstage-org/limelight#62]
Relates to #59 

- Tags should be assignable to Stage objects in a many-to-many relationship
- Association resource to be created
- Association is destroyed on destruction of either the Stage object or the Tag object

**Comment by rohrlach** [comment]
Due for deployment in 35 minutes

**Comment by vickis** [comment]
ok back on board

**Comment by helenvarley** [comment]
tested - added tags to walkthrough stage, removed one, all working as expected :+1:
