### ISSUE TITLE
Tag/Avatar Assignments

### ISSUE THREAD

**Issue by rohrlach** [upstage-org/limelight#63]
Relates to #59 

- Tags should be assignable to Avatar objects in a many-to-many relationship
- Association resource to be created
- Association is destroyed on destruction of either the Avatar object or the Tag object

**Comment by rohrlach** [comment]
Due to deploy in 50 mins

**Comment by helenvarley** [comment]
tested on the avatar Snoopy, successfully added and deleted a tag. 
(not able to test on another avatars as upload doesn't work but i assume that's coming)

**Comment by rohrlach** [comment]
Upload doesn't work?

Can you submit a bug for that?

**Comment by helenvarley** [comment]
done
