### ISSUE TITLE
Shout command is confusing

### ISSUE THREAD

**Issue by rohrlach** [upstage-org/limelight#7]
It makes little sense to have a dropdown that suggests the user can select their recipient also contain the ability to shout.

- [ ] Make chat "Shout" modifier a checkbox

**Comment by blankgaming** [comment]
Hi Paul,
Jason and I(Kit)  had created a check_box_tag but we cant modify the check box to be able to shout or broadcast on its on, we tried looking into the "<option class=....>" , we are not sure on how the data-chat-mode is linked to the message_type. We cant set the option class in the checkbox without a dropdown.

**Comment by blankgaming** [comment]
option class*, we are not sure....

**Comment by rohrlach** [comment]
Can you try to make sure you push your code up into the repo regularly? That way I can actually see what you've done and can reference it here.

**Comment by blankgaming** [comment]
Yes, sure. Will do so in the future.  Sorry for not uploading it.

**Comment by rohrlach** [comment]
Not a problem - it just makes life easier

**Comment by rohrlach** [comment]
@blankgaming @Tawpin how's this going? it's now well behind schedule.

**Comment by helenvarley** [comment]
from a user perspective, selecting "shout" from a dropdown menu is considerably slower than the previous method of simply typing ! before your text. is it possible to have both options? the dropdown menu is easier for newbies, but the ! method is much faster.

**Comment by helenvarley** [comment]
also with the dropdown menu, it should only work once - i.e. it makes the next line of text be a shout, then defaults back to normal. at least, i think this is how it should be ... @vickis can you comment?

**Comment by rohrlach** [comment]
@helenvarley We're currently working to switch it to a check box - I think we SHOULD add syntactical shortcuts - But as a separate issue as an extension to this one :)

**Comment by rohrlach** [comment]
@blankgaming @Tawpin - Could you please leave this and focus on your sprint 3 tickets?
