### ISSUE TITLE
shortcuts

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/limelight#72]
please can we have keyboard or syntactical shortcuts for common things, e.g. still being able to use ! to activate shouting mode as a quicker method than the dropdown menu.

**Comment by rohrlach** [comment]
@helenvarley You'll need to provide a list of specifically all the shortcuts you want ;)

**Comment by helenvarley** [comment]
ok; this requires some time, & for sure i won't think of them all at once. @vickis will no doubt have some ideas on it too.

**Comment by helenvarley** [comment]
- [ ] type ! before text to activate shouting mode

- [ ] type : before text to activate thinking mode
