### ISSUE TITLE
splash message - clickable links

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/limelight#75]
links posted in the splash message (the text that displays while the stage is loading, & at the beginning of a blank chat window) should be clickable & open in a new tab (the same as other links in the chat window).

**Comment by rohrlach** [comment]
Fair enough.. But as it stands, we don't actually NEED a loading screen ;)

...yet

**Comment by helenvarley** [comment]
hah - good point! then what about just having intro text in the chat window? this is useful, to have something there when people arrive too early.

actually, it would be a nice feature to be able to put a sign onto the stage - this has come up before - some kind of text message that can be placed on the stage before/after shows (or even used in performance) to ensure that everyone in the audience sees a message. 

i will make an issue for this, based on the assumption of not needing a splash screen.

**Comment by rohrlach** [comment]
Superseded by #83
