### ISSUE TITLE
Announcements

### ISSUE THREAD

**Issue by rohrlach** [upstage-org/limelight#8]
Create an Announcements resource that will display in the foyer.

**Acceptance Criteria**

- [x] Announcement is a standard resource that has no dependencies.
- [x] Announcements should have a title and body text
- [x] Logged in administrator can create, edit, delete announcements.
- [x] Foyer displays announcements to any user sorted latest-on-top.

**Comment by helenvarley** [comment]
announcements would be a great feature :)

**Comment by vickis** [comment]
agreed :)

**Comment by rohrlach** [comment]
Deployment in 5

**Comment by helenvarley** [comment]
looks great :) 
can only admins create announcements? & are these announcements visible to the public or only to logged in players? could it be possible to set individual announcements to be public or players only?
i added an image to one of my tests, & it isn't possible to resize images. this would be a helpful feature.

**Comment by helenvarley** [comment]
just reporting that i received the emails of my announcements :)
do they go to all players? would it be possible to select, e.g. to send to all players who are assigned to a particular stage?

**Comment by rohrlach** [comment]
In time, yes.  Actually, this is the start of a subscription module I have planned.

**Comment by rohrlach** [comment]
Closing this as initial requirements met
