### ISSUE TITLE
avatar upload doesn't work

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/limelight#84]
i'm not able to upload an avatar, because there is no "browse" button visible on the upload screen https://limelight.upstage.org.nz/avatars/new (when i go to "create new media" there is a "browse" button between the "name" and "image" fields).
![create_new_avatar](https://cloud.githubusercontent.com/assets/3437324/25746418/a5b37956-31a3-11e7-99c3-79603801ebb3.png)

**Comment by rohrlach** [comment]
This is actually by design.  Avatars reference an existing Media record rather than holding that information themselves.  This is so we can optimize disk usage etc. in the instance where the same image may be used as an Avatar, Prop, Wallpaper etc.

I've raised #85 in the interest of a better user experience

**Comment by helenvarley** [comment]
ok; but it's not clear to me how i make something an avatar. snoopy shows up in the media list & also in the avatar list, & in a dropdown menu. but if i want to make lady godiva into an avatar, what do i do?
and where do i assign voices?
and what about uploading a series of pngs? (or are there going be other options for animations?)

**Comment by rohrlach** [comment]
The fact that the name snoopy shows up twice is simply because I named the Medium instance Snoopy as well as the Avatar.

We don't have voices yet - But it'll be the same page

**Comment by helenvarley** [comment]
ok. & what about formats? (png, jpg, gif, swf ... ??) & a series of images?

**Comment by rohrlach** [comment]
Don't know yet - I'm overhauling the upload process at the moment
