### ISSUE TITLE
Audio Resource

### ISSUE THREAD

**Issue by rohrlach** [upstage-org/limelight#90]
- [ ] Belongs to a Medium record
- [ ] Nested Medium creation
- [ ] Has name
- [ ] Soft destroy
- [ ] Slugged URI

**Comment by helenvarley** [comment]
not sure what we should test here - i have successfully uploaded 2 sound files, one mp3 & one wav. 
i also tested deleting one of them, it worked. (then i reuploaded it).

**Comment by rohrlach** [comment]
That's tested enough for me 🙂
