### ISSUE TITLE
Migrate Avatars to Paperclip

### ISSUE THREAD

**Issue by rohrlach** [upstage-org/limelight#96]
Rather than using naive file upload code that we must maintain ourselves, let's use [Paperclip](https://github.com/thoughtbot/paperclip) gem

**Comment by rohrlach** [comment]
Do this before #95

**Comment by rohrlach** [comment]
@helenvarley @vickis The goal of testing here is basically to see if Avatars aren't broken

**Comment by helenvarley** [comment]
i successfully added a .png avatar, gave it a name & a tag, & assigned it to the walkthrough stage.

**Comment by helenvarley** [comment]
i added a jpg file & this also worked, but .swf did not.

**Comment by rohrlach** [comment]
Yes swf is flash - we're ditching flash

**Comment by rohrlach** [comment]
@helenvarley based on your feedback, I consider this issue resolved.
